window.venues = [
  {
    id: 1,
    name: "King Taps",
    neighbourhood: "King West",
    address: "620 King St W",
    lat: 43.6443,
    lng: -79.4044,
    days: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
    time_start: "15:00",
    time_end: "18:00",
    deal: "50% off wine · $6 domestic beer · $8 cocktails",
    vibes: ["lively","sports-tv","sidewalk-patio"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 2,
    name: "The Rabbit Hole",
    neighbourhood: "Financial District",
    address: "62 Wellington St E",
    lat: 43.6480,
    lng: -79.3745,
    days: ["Mon","Tue","Wed","Thu","Fri","Sat"],
    time_start: "15:00",
    time_end: "18:00",
    deal: "$6.95 draught · $10 wine · $12 cocktails",
    vibes: ["lively","upscale","sidewalk-patio"],
    last_scraped: "2026-05",
    source_url: "https://www.tastetoronto.com/guides/the-best-places-to-get-happy-hour-drinks-in-the-financial-district"
  },
  {
    id: 3,
    name: "CRAFT Beer Market",
    neighbourhood: "Financial District",
    address: "1 King St W",
    lat: 43.6484,
    lng: -79.3793,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "15:00",
    time_end: "18:00",
    deal: "$6 domestic · $7 craft beer · $9 cocktails",
    vibes: ["lively","sports-tv","sidewalk-patio"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 4,
    name: "Oretta",
    neighbourhood: "King West",
    address: "633 King St W",
    lat: 43.6444,
    lng: -79.4050,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "15:00",
    time_end: "19:00",
    deal: "$8 wine · $11 cocktails · $6 beer",
    vibes: ["upscale","sidewalk-patio"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 5,
    name: "Baro",
    neighbourhood: "King West",
    address: "485 King St W",
    lat: 43.6448,
    lng: -79.3998,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "17:00",
    time_end: "19:00",
    deal: "$12 cocktails · $6 beer · $9 wine",
    vibes: ["lively","upscale","rooftop"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 6,
    name: "Gusto 101",
    neighbourhood: "King West",
    address: "619 King St W",
    lat: 43.6444,
    lng: -79.4042,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "15:00",
    time_end: "18:00",
    deal: "$7 Aperol Spritz · $8 Negroni · $6 wine",
    vibes: ["upscale","sidewalk-patio","lively"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 7,
    name: "Bar Hop",
    neighbourhood: "Entertainment District",
    address: "391 King St W",
    lat: 43.6448,
    lng: -79.3957,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "16:00",
    time_end: "19:00",
    deal: "$6 craft beer · $9 wine · $10 cocktails",
    vibes: ["lively","dive-bar","sidewalk-patio"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 8,
    name: "Lapinou",
    neighbourhood: "King West",
    address: "637 King St W",
    lat: 43.6443,
    lng: -79.4052,
    days: ["Tue","Wed","Thu","Fri","Sat"],
    time_start: "17:00",
    time_end: "19:00",
    deal: "$10 cocktails · Tue–Wed 50% off wine bottles",
    vibes: ["quiet","upscale"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 9,
    name: "Hy's Steakhouse",
    neighbourhood: "Financial District",
    address: "365 Bay St",
    lat: 43.6500,
    lng: -79.3811,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "15:00",
    time_end: "18:00",
    deal: "$9 classic martini · $8 wine · $7 beer",
    vibes: ["upscale","quiet"],
    last_scraped: "2026-05",
    source_url: "https://www.tastetoronto.com/guides/the-best-places-to-get-happy-hour-drinks-in-the-financial-district"
  },
  {
    id: 10,
    name: "The Joneses",
    neighbourhood: "Financial District",
    address: "33 Yonge St",
    lat: 43.6467,
    lng: -79.3773,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "14:30",
    time_end: "18:00",
    deal: "$9 cocktails · $9 wine · $6 beer",
    vibes: ["lively","sidewalk-patio"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 11,
    name: "Cktl & Co",
    neighbourhood: "Financial District",
    address: "330 Bay St",
    lat: 43.6497,
    lng: -79.3808,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "14:00",
    time_end: "17:00",
    deal: "$7 wine · $7 beer",
    vibes: ["quiet","upscale"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 12,
    name: "Coffee Oysters Champagne",
    neighbourhood: "Entertainment District",
    address: "270 King St W",
    lat: 43.6471,
    lng: -79.3879,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "16:00",
    time_end: "18:00",
    deal: "$9 sparkling wine · $8 cocktails",
    vibes: ["upscale","quiet"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 13,
    name: "The Carbon Bar",
    neighbourhood: "Old Town",
    address: "99 Queen St E",
    lat: 43.6529,
    lng: -79.3714,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "15:00",
    time_end: "18:00",
    deal: "$7 beer · $9 bourbon cocktails",
    vibes: ["lively","upscale","live-music"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 14,
    name: "Amsterdam Brewhouse",
    neighbourhood: "Harbourfront",
    address: "245 Queens Quay W",
    lat: 43.6383,
    lng: -79.3849,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "15:00",
    time_end: "18:00",
    deal: "$6 draft beer · $8 cocktails",
    vibes: ["lively","sports-tv","sidewalk-patio"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 15,
    name: "Harriet's Rooftop",
    neighbourhood: "Entertainment District",
    address: "80 Blue Jays Way",
    lat: 43.6450,
    lng: -79.3913,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "16:00",
    time_end: "19:00",
    deal: "$10 cocktails · $8 wine · $7 beer",
    vibes: ["rooftop","upscale","lively"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 16,
    name: "Chotto Matte",
    neighbourhood: "Financial District",
    address: "161 Bay St",
    lat: 43.6484,
    lng: -79.3800,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "16:00",
    time_end: "18:00",
    deal: "$10–12 cocktails · $13 wine",
    vibes: ["upscale","lively"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 17,
    name: "Aera",
    neighbourhood: "King West",
    address: "456 Wellington St W",
    lat: 43.6421,
    lng: -79.4002,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "16:00",
    time_end: "19:00",
    deal: "$12 cocktails · $9 wine · $7 beer",
    vibes: ["rooftop","upscale","lively"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 18,
    name: "Melrose on Adelaide",
    neighbourhood: "Entertainment District",
    address: "481 Adelaide St W",
    lat: 43.6479,
    lng: -79.3987,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "15:00",
    time_end: "18:00",
    deal: "$7 beer · $9 cocktails · $8 wine",
    vibes: ["lively","upscale"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 19,
    name: "Patria",
    neighbourhood: "King West",
    address: "478 King St W",
    lat: 43.6447,
    lng: -79.3990,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "16:00",
    time_end: "18:00",
    deal: "$9 sangria · $8 wine · $10 cocktails",
    vibes: ["upscale","lively","sidewalk-patio"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  },
  {
    id: 20,
    name: "The Parlour",
    neighbourhood: "King West",
    address: "642 King St W",
    lat: 43.6443,
    lng: -79.4056,
    days: ["Mon","Tue","Wed","Thu","Fri"],
    time_start: "16:00",
    time_end: "18:00",
    deal: "$7 beer · $9 cocktails · $8 wine",
    vibes: ["lively","sidewalk-patio","sports-tv"],
    last_scraped: "2026-05",
    source_url: "https://www.fringinto.com/best-happy-hours-toronto/"
  }
];
